services:
  mysql:
    container_name: mysql-time-tracker
    image: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - mysql-volume:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - time-tracker-network
    restart: unless-stopped

#  time-tracker-api:
#    container_name: time-tracker-api
#    image: time-tracker:1.0.1
#    ports:
#      - 9192:9192
#    networks:
#      - time-tracker-network
#    depends_on:
#      - mysql
#
#  time-tracker-ui:
#    container_name: time-tracker-ui
#    image: time-tracker-ui:1.0.1
#    ports:
#      - 80:80
#    networks:
#      - time-tracker-network
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - time-tracker-api
#      - keycloak

  keycloak:
    container_name: keycloak-time-tracker
    image: quay.io/keycloak/keycloak:24.0.2
    env_file:
      - .env
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: mysql
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_HTTP_ENABLED: 'true'
    networks:
      - time-tracker-network
    depends_on:
      - mysql
    command:
      - "start-dev"
    restart: unless-stopped

  broker:
    image: apache/kafka:3.8.1
    container_name: broker
    ports:
      - 9092:9092
    networks:
      - time-tracker-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - time-tracker-network
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--appendfsync", "everysec",
        "--save", "900 1", "--save", "300 10", "--save", "60 10000",
        "--maxmemory", "512mb",
        "--maxmemory-policy", "allkeys-lru",
        "--bind", "127.0.0.1",
        "--tcp-keepalive", "60",
        "--loglevel", "notice",
        "--slowlog-log-slower-than", "10000",
        "--slowlog-max-len", "128"
      ]
    restart: unless-stopped


networks:
  time-tracker-network:
    driver: bridge

volumes:
  mysql-volume:
  redis-data:
